from pyisomme.report.euro_ncap.frontal_50kmh import EuroNCAP_Frontal_50kmh
from pyisomme.report.euro_ncap.side_barrier import EuroNCAP_Side_Barrier
from pyisomme.report.euro_ncap.side_pole import EuroNCAP_Side_Pole